# .github/workflows/backend.yml
name: Backend CI & CD

on:
  push:
    paths:
      - "backend-springboot/TheBlog/**"
      - ".github/workflows/backend.yml"
  pull_request:
    paths:
      - "backend-springboot/TheBlog/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-springboot/TheBlog

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn clean install

      # - name: Run tests
      #   run: mvn test

      - name: Trigger Render Deployment
        if: success()
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
